import type { SurveyDefinition } from './definition';

/**
 * Turns a checked survey definition into one transaction of SQL.
 *
 * Re-runnable. The survey row is upserted on its slug, and its questions and
 * options are replaced wholesale, so the database always matches the file.
 * Status and the preview token are set on the first run and never touched
 * again: publishing is a separate, deliberate `update ... set status = 'live'`.
 *
 * Replacing questions is safe for stored answers, because answers are keyed by
 * question and option keys, not row ids. Renaming a key is not: answers stored
 * against the old key stop matching anything. Keys are for life once a survey
 * has responses.
 */

function lit(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'null::text';
  return `'${value.replace(/'/g, "''")}'::text`;
}

function int(value: number | null | undefined): string {
  if (value === null || value === undefined) return 'null::smallint';
  if (!Number.isInteger(value)) throw new Error(`Not an integer: ${value}`);
  return `${value}::smallint`;
}

function textArray(values: readonly string[] | undefined): string {
  if (!values || values.length === 0) return `'{}'::text[]`;
  return `array[${values.map((v) => lit(v)).join(', ')}]::text[]`;
}

export function definitionToSql(
  def: SurveyDefinition,
  previewToken: string,
  source: string
): string {
  const slug = lit(def.slug);

  const questionRows = def.questions.map((q, position) =>
    [
      lit(q.key),
      int(position),
      lit(q.kind),
      lit(q.prompt),
      lit(q.hint),
      q.required === false ? 'false' : 'true',
      int(q.minChoices),
      int(q.maxChoices),
      int(q.maxLength),
      textArray(q.optionsFrom),
      textArray(q.showIf),
    ].join(', ')
  );

  const optionRows = def.questions.flatMap((q) =>
    (q.options ?? []).map((o, position) =>
      [lit(q.key), lit(o.key), int(position), lit(o.label), lit(o.hint), lit(o.icon)].join(', ')
    )
  );

  const lines = [
    `-- Generated by scripts/survey-to-sql.ts from ${source}. Do not edit by hand.`,
    '-- Re-running replaces the questions and options and leaves status and preview_token alone.',
    'begin;',
    '',
    'insert into public.surveys (',
    '  slug, eyebrow, title, intro, minutes, share_text, thank_you_heading, thank_you_body,',
    '  results_question_key, results_heading, results_min_responses, consent_text, preview_token',
    ') values (',
    `  ${slug}, ${lit(def.eyebrow)}, ${lit(def.title)}, ${lit(def.intro)}, ${int(def.minutes)},`,
    `  ${lit(def.shareText)}, ${lit(def.thankYouHeading)}, ${lit(def.thankYouBody)},`,
    `  ${lit(def.results?.questionKey)}, ${lit(def.results?.heading)}, ${def.results?.minResponses ?? 20},`,
    `  ${lit(def.consentText)}, ${lit(previewToken)}`,
    ')',
    'on conflict (slug) do update set',
    '  eyebrow = excluded.eyebrow,',
    '  title = excluded.title,',
    '  intro = excluded.intro,',
    '  minutes = excluded.minutes,',
    '  share_text = excluded.share_text,',
    '  thank_you_heading = excluded.thank_you_heading,',
    '  thank_you_body = excluded.thank_you_body,',
    '  results_question_key = excluded.results_question_key,',
    '  results_heading = excluded.results_heading,',
    '  results_min_responses = excluded.results_min_responses,',
    '  consent_text = excluded.consent_text;',
    '',
    `delete from public.survey_questions where survey_id = (select id from public.surveys where slug = ${slug});`,
    '',
    'insert into public.survey_questions (',
    '  survey_id, key, position, kind, prompt, hint, required,',
    '  min_choices, max_choices, max_length, options_from, show_if',
    ')',
    'select s.id, v.key, v.position, v.kind, v.prompt, v.hint, v.required,',
    '  v.min_choices, v.max_choices, v.max_length, v.options_from, v.show_if',
    'from public.surveys s',
    'cross join (values',
    questionRows.map((row) => `  (${row})`).join(',\n'),
    ') as v (key, position, kind, prompt, hint, required, min_choices, max_choices, max_length, options_from, show_if)',
    `where s.slug = ${slug};`,
    '',
  ];

  if (optionRows.length > 0) {
    lines.push(
      'insert into public.survey_options (survey_id, question_id, key, position, label, hint, icon)',
      'select q.survey_id, q.id, v.key, v.position, v.label, v.hint, v.icon',
      'from public.survey_questions q',
      `join public.surveys s on s.id = q.survey_id and s.slug = ${slug}`,
      'join (values',
      optionRows.map((row) => `  (${row})`).join(',\n'),
      ') as v (question_key, key, position, label, hint, icon) on v.question_key = q.key;',
      ''
    );
  }

  lines.push('commit;', '');
  return lines.join('\n');
}
