/**
 * The reviewed allowlist of database objects the `anon` role can reach.
 *
 * WHAT THIS IS
 *   A committed record of exactly what the public anon key can touch in the
 *   `public` schema of the Orange Jelly project, as reviewed by a human. Every
 *   entry below was read from the live catalogue, checked against what the site
 *   actually needs, and kept deliberately.
 *
 *   `src/test/anon-access.test.ts` reads the live catalogue and fails when the
 *   database grants anon anything this file does not allow. It skips with an
 *   explanation when no database connection is configured, so it is inert by
 *   default and only speaks when pointed at a real project.
 *
 * WHY IT EXISTS
 *   Anon reach has drifted repeatedly across this workspace, silently, because
 *   `pg_default_acl` widens the surface on its own. On this project the default
 *   privileges for schema `public` hand `anon` every table privilege on every
 *   new table, EXECUTE on every new function and read plus write on every new
 *   sequence, under both the `postgres` and `supabase_admin` owner roles. Nobody
 *   writes those grants. They arrive with the next `create table`.
 *
 *   No migration in this repository revokes those default privileges, so this
 *   allowlist is the detection that stands in for a fix that has not been made.
 *   Writing that revoke migration is a separate, deliberate piece of work.
 *
 *   What this database holds raises the stakes. `contacts` carries the name,
 *   email address, phone number, pub name and free-text message of real
 *   prospects. `newsletter_subscribers` carries email addresses and consent
 *   timestamps. `polls` and `poll_participants` carry organiser and participant
 *   names, email addresses and edit tokens. All of it is personal data belonging
 *   to identifiable people, so anon reach here is a data protection problem
 *   before it is a commercial one.
 *
 * WHAT MUST NEVER APPEAR IN THIS FILE
 *   No table or view carrying lead or contact data may ever be granted SELECT to
 *   anon in a way this file blesses. Those relations are named in
 *   `LEAD_BEARING_RELATIONS` below and the rule is enforced two ways rather than
 *   merely written down:
 *
 *     1. None of them may appear here as a `view` or `materialized view` at all.
 *        A view runs with its owner's rights and therefore steps straight past
 *        the row level security that is currently the only thing keeping anon
 *        out of these tables. An anon-readable view over `contacts` would be a
 *        live leak of prospect data on the day it was created, whatever the RLS
 *        on the underlying table says. This is not hypothetical: an owner-rights
 *        view is how the same class of leak was found on a sibling project in
 *        this workspace in August 2026.
 *     2. `LEAD_EXPOSURE_QUERY` checks the live database directly, and the test
 *        fails if RLS is ever switched off on one of these tables or if any
 *        policy hands anon or PUBLIC a SELECT path into it.
 *
 *   If the live catalogue ever reports one of those, the fix is a migration that
 *   revokes or drops it, never an edit to this file.
 *
 * HOW TO UPDATE IT, DELIBERATELY
 *   1. Do not edit this file to make a failing test pass. A failure means the
 *      live database changed. Find out which migration changed it first.
 *   2. If the new reach is wanted, add the entry with a `why` that names the
 *      feature that needs it and the migration that granted it, in the same pull
 *      request as that migration.
 *   3. If the new reach is not wanted, write a migration that revokes it. The
 *      shape that actually closes it revokes from PUBLIC and anon together,
 *      because `create function` grants PUBLIC its own EXECUTE and anon is a
 *      member of PUBLIC:
 *        `revoke execute on function public.thing(...) from public, anon;`
 *   4. Re-run the test with `DATABASE_URL` set to the project's direct Postgres
 *      URL, and paste the result into the pull request.
 *
 * A NOTE ON THE TABLE ENTRIES
 *   Anon holds every table privilege on every table in `public`. That is not a
 *   decision anyone here made: it is what the Supabase default privileges grant.
 *   Row level security is therefore the control, and every table below has RLS
 *   enabled with zero policies, which denies everything to every role except the
 *   service role that bypasses RLS entirely.
 *
 *   The `why` on each entry records what anon can actually do, checked against
 *   the live REST API with the public anon key, not inferred from the schema.
 *   The value of listing the tables is that a NEW table shows up here as a
 *   failure on the day it is created, while it is still empty.
 *
 * A NOTE ON THE WRITE PATH
 *   The lead capture form does not need an anon insert grant and does not use
 *   one. Every write in `src/lib/db/leads.ts`, `src/lib/db/enquiries.ts` and
 *   `src/lib/db/polls.ts` goes through `getSupabaseAdminClient()`, the
 *   service-role client, from a server route. Anon holds the INSERT privilege on
 *   these tables as part of the same default grant, but RLS with no policies
 *   blocks it, and nothing in the site relies on it. So there is no insert-only
 *   exception to carve out here, and no reason to ever add one.
 *
 * EVIDENCE
 *   Read from project miqqkllqfyvaomzgujed on 4 September 2026, read-only.
 *   Nothing was granted, revoked or migrated to produce it. At that reading
 *   `contacts` held 9 rows, `conversion_events` 40, `lead_sources` 45 and
 *   `poll_rate_limits` 2, and a REST read with the public anon key returned an
 *   empty array for all nine tables. Empty results from populated tables are the
 *   point: they prove RLS is doing the work, rather than the tables being bare.
 */

export type AnonObjectKind = 'table' | 'view' | 'materialized view' | 'sequence' | 'function';

/** One object the live catalogue says anon can reach. */
export interface AnonCatalogueEntry {
  kind: AnonObjectKind;
  /** Tables, views and sequences use the bare relation name. Functions use
   *  `name(identity arguments)`, so an overload cannot hide behind its sibling. */
  name: string;
  privileges: string[];
}

export interface AnonAllowlistEntry extends AnonCatalogueEntry {
  why: string;
}

/**
 * Every table privilege Postgres 17 can grant. MAINTAIN is 17 only, so the
 * catalogue query asks for it only when the server is new enough. This project
 * runs 17.6, so it is asked for and it is held.
 */
export const TABLE_PRIVILEGES = [
  'SELECT',
  'INSERT',
  'UPDATE',
  'DELETE',
  'TRUNCATE',
  'REFERENCES',
  'TRIGGER',
] as const;

export const TABLE_PRIVILEGES_PG17 = [...TABLE_PRIVILEGES, 'MAINTAIN'] as const;

export const SEQUENCE_PRIVILEGES = ['SELECT', 'UPDATE', 'USAGE'] as const;

/** What the Supabase default privileges hand anon on every table in `public`. */
const SUPABASE_DEFAULT_TABLE_GRANT = [
  'DELETE',
  'INSERT',
  'MAINTAIN',
  'REFERENCES',
  'SELECT',
  'TRIGGER',
  'TRUNCATE',
  'UPDATE',
];

/** Shared wording, because the reason really is identical on these tables. */
const RLS_CLOSED =
  'Grant is the Supabase default, not a decision. RLS is enabled with zero policies, which denies every role except the service role that bypasses RLS. Verified: the REST API returns an empty array to the public anon key.';

/**
 * Relations that carry lead or contact data. These may never be reachable by
 * anon through a view, and RLS on them may never be switched off or opened to
 * anon by a policy. Both rules are enforced by `src/test/anon-access.test.ts`.
 */
export const LEAD_BEARING_RELATIONS: readonly string[] = [
  // Names, email addresses, phone numbers, pub names and free-text messages
  // from the contact and enquiry forms.
  'contacts',
  // Email addresses and consent timestamps.
  'newsletter_subscribers',
  // Normalised email addresses joined to named conversion events.
  'conversion_events',
  // Attribution rows keyed to a contact or subscriber by owner_type/owner_id.
  'lead_sources',
  // Organiser name, organiser email and the tokens that unlock a poll.
  'polls',
  // Participant display names, email addresses and edit tokens.
  'poll_participants',
  // Joins a named participant to what they answered.
  'poll_responses',
];

/**
 * The reviewed set. Anything the live catalogue reports that is not here fails
 * the test, and so does anything here that the live catalogue reports with more
 * privileges than listed.
 */
export const ANON_ALLOWLIST: readonly AnonAllowlistEntry[] = [
  {
    kind: 'table',
    name: 'contacts',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: `${RLS_CLOSED} This is the lead table: name, email, phone, pub name and message. Writes reach it only through getSupabaseAdminClient() in src/lib/db/enquiries.ts and src/lib/db/leads.ts, and reads only through the admin routes under /api/admin.`,
  },
  {
    kind: 'table',
    name: 'conversion_events',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: `${RLS_CLOSED} Holds normalised email addresses against named events, so it is lead data in its own right and not merely analytics.`,
  },
  {
    kind: 'table',
    name: 'lead_sources',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: `${RLS_CLOSED} Attribution rows pointing at a contact or a subscriber through owner_type and owner_id, which makes them lead data by reference.`,
  },
  {
    kind: 'table',
    name: 'newsletter_subscribers',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: `${RLS_CLOSED} Email addresses and consent timestamps. Signup writes go through the service-role client in src/lib/db/leads.ts.`,
  },
  {
    kind: 'table',
    name: 'poll_options',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: `${RLS_CLOSED} The dates and times offered by a poll. Participant and organiser pages read it through server components that use the service-role client, never from the browser.`,
  },
  {
    kind: 'table',
    name: 'poll_participants',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: `${RLS_CLOSED} Display names, email addresses and per-participant edit tokens. An anon read here would hand over the tokens that let anyone edit someone else's response.`,
  },
  {
    kind: 'table',
    name: 'poll_rate_limits',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: `${RLS_CLOSED} Counters only, keyed by a peppered hash rather than a raw address. Written through poll_rate_limit_hit(), whose EXECUTE was explicitly revoked from public, anon and authenticated by 20260716190000_poll_rate_limits.sql. That revoke is the pattern every new function here should copy.`,
  },
  {
    kind: 'table',
    name: 'poll_responses',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: `${RLS_CLOSED} Ties a named participant to their answers, so it is personal data by reference.`,
  },
  {
    kind: 'table',
    name: 'polls',
    privileges: SUPABASE_DEFAULT_TABLE_GRANT,
    why: `${RLS_CLOSED} Organiser name, organiser email, and the participant, organiser, verify and resend tokens. Those tokens are the whole access control model for the availability feature, so an anon read here would be equivalent to publishing them.`,
  },
  // contacts_touch_updated_at() and set_updated_at() were listed here until
  // migration 20260905053124 revoked anon's EXECUTE on them. Leaving them listed
  // would let that grant come back unnoticed, so they are gone.
];

/**
 * Anon reach that has been reviewed, is NOT approved, and has not been closed
 * yet. Listing it here does not allow it: the test still fails on it. The point
 * is that the failure reads as a known open item with a decision attached rather
 * than as fresh drift, and that it stays visible until it is dealt with.
 *
 * Empty at the 4 September 2026 reading. Every object anon could reach was
 * either reviewed and allowlisted above or absent from the database.
 */
export interface AnonOpenItem {
  kind: AnonObjectKind;
  name: string;
  why: string;
}

export const ANON_OPEN_ITEMS: readonly AnonOpenItem[] = [];

/**
 * The catalogue query the test runs against the live database. Read-only.
 *
 * It asks `has_*_privilege` rather than reading ACL arrays, because that is the
 * question worth answering: what anon can actually do, including anything it
 * inherits through PUBLIC. Functions are keyed by identity arguments so an
 * overload cannot hide behind a sibling with the same name.
 */
export const ANON_CATALOGUE_QUERY = `
with table_privs as (
  select case when current_setting('server_version_num')::int >= 170000
              then array[${TABLE_PRIVILEGES_PG17.map((p) => `'${p}'`).join(',')}]
              else array[${TABLE_PRIVILEGES.map((p) => `'${p}'`).join(',')}] end as names
),
rel as (
  select case c.relkind when 'r' then 'table' when 'p' then 'table'
                        when 'v' then 'view' when 'm' then 'materialized view' end as kind,
         c.relname as name,
         (select coalesce(array_agg(p order by p), array[]::text[])
            from table_privs, unnest(table_privs.names) p
           where has_table_privilege('anon', c.oid, p)) as privileges
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind in ('r','p','v','m')
),
seq as (
  select 'sequence' as kind, c.relname as name,
         (select coalesce(array_agg(p order by p), array[]::text[])
            from unnest(array[${SEQUENCE_PRIVILEGES.map((p) => `'${p}'`).join(',')}]) p
           where has_sequence_privilege('anon', c.oid, p)) as privileges
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind = 'S'
),
fn as (
  select 'function' as kind,
         p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')' as name,
         array['EXECUTE'] as privileges
    from pg_proc p
   where p.pronamespace = 'public'::regnamespace
     and has_function_privilege('anon', p.oid, 'EXECUTE')
)
select coalesce(json_agg(row_to_json(x) order by x.kind, x.name), '[]'::json) as reachable
  from (
    select * from rel where cardinality(privileges) > 0
    union all select * from seq where cardinality(privileges) > 0
    union all select * from fn
  ) x;
`.trim();

/**
 * The second live check, and the one that actually answers "can anon read a
 * lead". The privilege diff above cannot answer it on its own, because anon
 * holds SELECT on every table by default and RLS is what stops it mattering.
 *
 * Read-only. Returns one row per table in `public` with RLS state and a count of
 * the policies that would give anon a SELECT path, whether named directly, held
 * through PUBLIC, or left unrestricted.
 */
export const LEAD_EXPOSURE_QUERY = `
select c.relname as name,
       c.relrowsecurity as rls_enabled,
       coalesce((
         select count(*) from pg_policies p
          where p.schemaname = 'public'
            and p.tablename = c.relname
            and p.cmd in ('SELECT', 'ALL')
            and (p.roles is null
                 or p.roles = '{public}'
                 or 'anon' = any(p.roles))
       ), 0)::int as anon_select_policies
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
 where n.nspname = 'public' and c.relkind in ('r','p')
 order by c.relname;
`.trim();

/** One table's row level security state, as read from the live database. */
export interface LeadExposureRow {
  name: string;
  rls_enabled: boolean;
  anon_select_policies: number;
}

/** One way a lead-bearing table is open to anon. */
export interface LeadExposureFinding {
  name: string;
  reason: string;
}

/**
 * Check the live RLS state of every lead-bearing table. A missing table is not
 * a finding: it may simply not exist yet in the database being checked, and the
 * privilege diff is what notices new relations.
 */
export function findLeadExposure(
  rows: readonly LeadExposureRow[],
  leadBearing: readonly string[] = LEAD_BEARING_RELATIONS
): LeadExposureFinding[] {
  const byName = new Map(rows.map((row) => [row.name, row]));
  const findings: LeadExposureFinding[] = [];

  for (const name of leadBearing) {
    const row = byName.get(name);
    if (!row) continue;

    if (!row.rls_enabled) {
      findings.push({
        name,
        reason:
          'row level security is disabled, so the default anon SELECT grant is live and this table is readable with the public anon key',
      });
    }

    if (row.anon_select_policies > 0) {
      findings.push({
        name,
        reason: `${row.anon_select_policies} policy or policies give anon or PUBLIC a SELECT path into this table`,
      });
    }
  }

  return findings;
}

/** A failure message for lead exposure that says what to do about it. */
export function describeLeadExposure(findings: readonly LeadExposureFinding[]): string {
  const lines = [
    `The public anon key can read lead or contact data from ${findings.length} relation(s).`,
    '',
  ];

  for (const finding of findings) {
    lines.push(`  LEAD DATA OPEN   ${finding.name}`, `                   ${finding.reason}`, '');
  }

  lines.push(
    'These tables carry personal data belonging to real prospects, so this is a',
    'data protection incident and not a configuration preference. Do not edit',
    'supabase/anon-access-allowlist.ts to make this pass. Write a migration that',
    're-enables row level security, or drops the policy that opened the table, and',
    'work out how long the data was reachable.'
  );

  return lines.join('\n');
}

/** One way the live database is wider than the allowlist. */
export interface AnonAccessFinding {
  kind: AnonObjectKind;
  name: string;
  /** `unlisted` is an object anon can reach that the allowlist does not mention.
   *  `widened` is a listed object holding privileges beyond those allowed. */
  problem: 'unlisted' | 'widened';
  extraPrivileges: string[];
  /** Set when this object is a reviewed, still-open item rather than new drift. */
  knownOpenItem?: string;
}

export interface AnonAccessDiff {
  findings: AnonAccessFinding[];
  /** Allowlisted objects the live database no longer grants, or grants less of.
   *  Not a failure: the world got tighter. Reported so the file can be trimmed. */
  stale: string[];
}

const keyOf = (kind: string, name: string): string => `${kind} ${name}`;

/**
 * Compare a live catalogue reading against the allowlist. Pure, so the rules are
 * unit-tested without a database.
 */
export function diffAnonAccess(
  reachable: readonly AnonCatalogueEntry[],
  allowlist: readonly AnonAllowlistEntry[] = ANON_ALLOWLIST,
  openItems: readonly AnonOpenItem[] = ANON_OPEN_ITEMS
): AnonAccessDiff {
  const allowed = new Map<string, AnonAllowlistEntry>(
    allowlist.map((entry) => [keyOf(entry.kind, entry.name), entry])
  );
  const open = new Map<string, AnonOpenItem>(
    openItems.map((item) => [keyOf(item.kind, item.name), item])
  );

  const findings: AnonAccessFinding[] = [];
  const seen = new Set<string>();

  for (const entry of reachable) {
    const key = keyOf(entry.kind, entry.name);
    seen.add(key);
    const allowedEntry = allowed.get(key);

    if (!allowedEntry) {
      const openItem = open.get(key);
      findings.push({
        kind: entry.kind,
        name: entry.name,
        problem: 'unlisted',
        extraPrivileges: [...entry.privileges].sort(),
        ...(openItem ? { knownOpenItem: openItem.why } : {}),
      });
      continue;
    }

    const permitted = new Set(allowedEntry.privileges);
    const extra = entry.privileges.filter((p) => !permitted.has(p)).sort();
    if (extra.length > 0) {
      findings.push({
        kind: entry.kind,
        name: entry.name,
        problem: 'widened',
        extraPrivileges: extra,
      });
    }
  }

  const stale = [...allowed.keys()].filter((key) => !seen.has(key)).sort();

  return { findings, stale };
}

/** A failure message that names the objects and says what to do about them. */
export function describeAnonAccessFindings(findings: readonly AnonAccessFinding[]): string {
  const lines = [
    `anon can reach ${findings.length} object(s) that supabase/anon-access-allowlist.ts does not allow.`,
    '',
  ];

  for (const finding of findings) {
    if (finding.problem === 'unlisted') {
      lines.push(
        `  NOT ALLOWLISTED  ${finding.kind} ${finding.name}`,
        `                   anon holds: ${finding.extraPrivileges.join(', ')}`
      );
      if (finding.knownOpenItem) {
        lines.push(
          '                   This is a reviewed, still-open item, not new drift:',
          `                   ${finding.knownOpenItem}`
        );
      }
    } else {
      lines.push(
        `  WIDENED          ${finding.kind} ${finding.name}`,
        `                   anon gained: ${finding.extraPrivileges.join(', ')}`
      );
    }
    lines.push('');
  }

  lines.push(
    'Do not edit the allowlist to make this pass. Find the migration that changed',
    'the database. If the reach is wanted, add it to the allowlist with a reason in',
    'the same pull request. If it is not, write a migration that revokes it, from',
    'PUBLIC and anon together, because create function grants PUBLIC its own EXECUTE',
    'and anon is a member of PUBLIC.',
    '',
    'If the new object is a table, check its RLS before anything else. A new table',
    'inherits the anon SELECT grant from pg_default_acl, so RLS is the only thing',
    'between the public anon key and whatever it holds.'
  );

  return lines.join('\n');
}
