import { type MetadataRoute } from 'next';

/**
 * The web app manifest.
 *
 * Replaces a hand-written `public/manifest.json` that called the site "Orange Jelly
 * - AI Tools for Pubs" and described it with a retired claim about hours. It is the
 * name that appears when someone adds the site to a home screen, so it had the old
 * position in the one place a person keeps.
 *
 * Generated by Next from this file, which means it goes through the same review as
 * everything else rather than sitting in `public/` where nothing reads it.
 *
 * The description is the site description in short form and has to move with it. It
 * said "Growth partner for ambitious small and mid-sized businesses" for three days
 * after the copy it was taken from had changed, because no gate covers this file.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Orange Jelly',
    short_name: 'Orange Jelly',
    description: 'Websites, bespoke applications and connected systems that help businesses grow.',
    start_url: '/',
    display: 'standalone',
    background_color: '#FCFBF9',
    theme_color: '#F76B0C',
    orientation: 'portrait-primary',
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    ],
    categories: ['business'],
    lang: 'en-GB',
    dir: 'ltr',
  };
}
