-- Surveys: fast, shareable, database-driven. Piece 1 of tasks/survey/PLAN.md.
--
-- A survey goes live by inserting rows, not by shipping code. That is the point
-- of Peter's decision on 22 September 2026. Survey copy is drafted as JSON in
-- content/surveys/ so the repo's language checks run on it, then turned into SQL
-- by scripts/survey-to-sql.mjs; what the site serves is always these rows.
--
-- Conventions follow 20260716150000_availability_polls.sql: timestamptz,
-- snake_case, <table>_<cols>_idx index naming, and RLS enabled with no policies
-- so only the service-role key reaches the data.
--
-- Two deliberate departures, both justified:
--   1. The definition tables (surveys, survey_questions, survey_options) default
--      their uuid ids. They are written by reviewed SQL from
--      scripts/survey-to-sql.mjs, not by the app, so there is no application
--      code to generate them. Responses and contacts are written by the app and
--      follow the house rule: the app generates the id and passes it in.
--   2. Research data is protected from a careless delete. Deleting a survey
--      cascades to its questions and options but is refused while it has
--      responses (on delete restrict). Answers are the reason the survey exists.

create table if not exists surveys (
  id                    uuid primary key default gen_random_uuid(),
  -- The public URL: /survey/<slug>.
  slug                  text not null unique
                        check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and char_length(slug) <= 60),
  status                text not null default 'draft'
                        check (status in ('draft', 'live', 'closed')),
  eyebrow               text not null,
  title                 text not null,
  intro                 text not null,
  -- "Takes about N minutes". An honest estimate, set by whoever writes the survey.
  minutes               smallint not null check (minutes between 1 and 15),
  -- The words that travel with a shared link (WhatsApp, Facebook, LinkedIn).
  share_text            text not null,
  thank_you_heading     text not null,
  thank_you_body        text not null,
  -- Which question the thank-you screen tallies. Null shows no results at all.
  results_question_key  text,
  results_heading       text,
  -- Results stay hidden until this many real responses exist, so nobody reads
  -- "100% chose X" off a single vote.
  results_min_responses integer not null default 20 check (results_min_responses >= 1),
  -- The line beside the consent tick on a contact step. The app refuses to
  -- serve a survey that has a contact step and no consent line.
  consent_text          text,
  -- Capability token for previewing a draft: /survey/<slug>?preview=<token>.
  -- CSPRNG, base64url, >= 128 bits, generated by scripts/survey-to-sql.mjs.
  preview_token         text not null unique check (char_length(preview_token) >= 22),
  opened_at             timestamptz,
  closed_at             timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

drop trigger if exists surveys_set_updated_at on surveys;
create trigger surveys_set_updated_at
  before update on surveys
  for each row execute function public.set_updated_at();

create table if not exists survey_questions (
  id            uuid primary key default gen_random_uuid(),
  survey_id     uuid not null references surveys (id) on delete cascade,
  -- Stable name used in answers, show_if and options_from. Never reuse a key
  -- for a different question once responses exist: answers are keyed by it.
  key           text not null check (key ~ '^[a-z0-9]+(_[a-z0-9]+)*$' and char_length(key) <= 40),
  position      smallint not null check (position >= 0),
  -- single: pick one. multi: pick between min_choices and max_choices.
  -- text: free text up to max_length. contact: the volunteer details step.
  kind          text not null check (kind in ('single', 'multi', 'text', 'contact')),
  prompt        text not null,
  hint          text,
  -- Only meaningful for single and text. multi uses min_choices instead.
  required      boolean not null default true,
  min_choices   smallint,
  max_choices   smallint,
  max_length    smallint,
  -- Piping: this question offers only the options picked in these earlier
  -- questions ("Of the ones you picked, which one matters most?").
  options_from  text[] not null default '{}',
  -- Shown only when any of these option keys was picked earlier. Empty: always.
  show_if       text[] not null default '{}',
  unique (survey_id, key),
  unique (survey_id, position),
  unique (id, survey_id),
  constraint survey_questions_choices_chk check (
    (kind = 'multi' and min_choices is not null and max_choices is not null
      and min_choices >= 0 and max_choices >= greatest(min_choices, 1))
    or (kind <> 'multi' and min_choices is null and max_choices is null)
  ),
  constraint survey_questions_text_chk check (
    (kind = 'text' and max_length between 1 and 2000)
    or (kind <> 'text' and max_length is null)
  ),
  constraint survey_questions_piping_chk check (
    kind in ('single', 'multi') or cardinality(options_from) = 0
  )
);

create index if not exists survey_questions_survey_id_idx on survey_questions (survey_id);

create table if not exists survey_options (
  id           uuid primary key default gen_random_uuid(),
  survey_id    uuid not null,
  question_id  uuid not null,
  -- Unique across the whole survey, not just the question, so show_if and
  -- piped answers can name an option without saying which question owns it.
  key          text not null check (key ~ '^[a-z0-9]+(_[a-z0-9]+)*$' and char_length(key) <= 40),
  position     smallint not null check (position >= 0),
  label        text not null,
  hint         text,
  -- A lucide icon name from the allow-list in src/lib/surveys/icons.ts.
  -- Anything else renders without an icon rather than failing.
  icon         text check (icon ~ '^[a-z0-9-]+$'),
  -- Composite key: an option can never belong to a question from another survey.
  foreign key (question_id, survey_id)
    references survey_questions (id, survey_id) on delete cascade,
  unique (survey_id, key),
  unique (question_id, position)
);

create index if not exists survey_options_question_id_idx on survey_options (question_id);

create table if not exists survey_responses (
  id             uuid primary key,
  survey_id      uuid not null references surveys (id) on delete restrict,
  -- { question_key: [option_key, ...] } for choices, { question_key: "text" }
  -- for free text. Validated by src/lib/surveys/logic.ts before it gets here;
  -- the app is the only writer.
  answers        jsonb not null check (jsonb_typeof(answers) = 'object'),
  -- Answers given through a preview link. Kept for testing, left out of every
  -- count and tally.
  is_preview     boolean not null default false,
  -- Attribution. A host, never a full referrer URL, and never an IP address.
  referrer_host  text,
  utm_source     text,
  utm_medium     text,
  utm_campaign   text,
  utm_term       text,
  utm_content    text,
  created_at     timestamptz not null default now(),
  unique (id, survey_id)
);

create index if not exists survey_responses_survey_id_created_at_idx
  on survey_responses (survey_id, created_at);

-- Personal data. The only table in this feature that holds any.
create table if not exists survey_contacts (
  id                uuid primary key,
  survey_id         uuid not null,
  response_id       uuid not null unique,
  name              text not null check (char_length(name) between 1 and 120),
  email             text not null check (char_length(email) between 3 and 254),
  email_normalized  text not null,
  business_name     text check (char_length(business_name) <= 120),
  -- The option keys that brought this person to the contact step, e.g.
  -- {say_call, test_early}. What they agreed to be contacted about.
  volunteered_for   text[] not null default '{}',
  -- The exact consent line they ticked, and when. Proof of consent.
  consent_text      text not null,
  consented_at      timestamptz not null,
  created_at        timestamptz not null default now(),
  foreign key (response_id, survey_id)
    references survey_responses (id, survey_id) on delete cascade
);

create index if not exists survey_contacts_survey_id_idx on survey_contacts (survey_id);

-- One transaction for the answers and, when given, the volunteer's details.
-- Either both land or neither does, so the app can report one honest outcome.
--
-- It re-checks that the survey is open inside the transaction: the app checks
-- first, but a survey closed between page load and submit must still refuse.
create or replace function public.submit_survey_response(
  p_response_id   uuid,
  p_survey_id     uuid,
  p_answers       jsonb,
  p_is_preview    boolean,
  p_referrer_host text,
  p_utm_source    text,
  p_utm_medium    text,
  p_utm_campaign  text,
  p_utm_term      text,
  p_utm_content   text,
  p_contact       jsonb
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.surveys s
    where s.id = p_survey_id
      and (s.status = 'live' or (p_is_preview and s.status = 'draft'))
  ) then
    raise exception 'survey_not_open' using errcode = 'P0001';
  end if;

  insert into public.survey_responses (
    id, survey_id, answers, is_preview, referrer_host,
    utm_source, utm_medium, utm_campaign, utm_term, utm_content
  ) values (
    p_response_id, p_survey_id, p_answers, p_is_preview, p_referrer_host,
    p_utm_source, p_utm_medium, p_utm_campaign, p_utm_term, p_utm_content
  );

  if p_contact is not null then
    insert into public.survey_contacts (
      id, survey_id, response_id, name, email, email_normalized, business_name,
      volunteered_for, consent_text, consented_at
    ) values (
      (p_contact ->> 'id')::uuid,
      p_survey_id,
      p_response_id,
      p_contact ->> 'name',
      p_contact ->> 'email',
      p_contact ->> 'email_normalized',
      p_contact ->> 'business_name',
      coalesce(
        array(select jsonb_array_elements_text(p_contact -> 'volunteered_for')),
        '{}'
      ),
      p_contact ->> 'consent_text',
      now()
    );
  end if;
end;
$$;

-- Every tally for one survey in one pass: (question_key, option_key, picks).
-- Free-text answers are strings, not arrays, so they contribute nothing here.
create or replace function public.survey_tallies(p_survey_id uuid)
returns table (question_key text, option_key text, picks bigint)
language sql
stable
security invoker
set search_path = ''
as $$
  select a.key as question_key, o.value as option_key, count(*) as picks
  from public.survey_responses r
  cross join lateral jsonb_each(r.answers) as a (key, value)
  cross join lateral jsonb_array_elements_text(
    case when jsonb_typeof(a.value) = 'array' then a.value else '[]'::jsonb end
  ) as o (value)
  where r.survey_id = p_survey_id
    and not r.is_preview
  group by a.key, o.value;
$$;

-- Server-only, like every other table here. RLS with no policies already stops
-- anon and authenticated; the revokes make that true of the grants as well.
alter table surveys enable row level security;
alter table survey_questions enable row level security;
alter table survey_options enable row level security;
alter table survey_responses enable row level security;
alter table survey_contacts enable row level security;

revoke all on table surveys, survey_questions, survey_options, survey_responses, survey_contacts
  from anon, authenticated;

-- Granted explicitly rather than inherited. Newer Supabase defaults no longer
-- grant new public tables to service_role, and a local stack built on them
-- refused every write until this line existed. Explicit is the same on both.
grant select, insert, update, delete
  on table surveys, survey_questions, survey_options, survey_responses, survey_contacts
  to service_role;

revoke execute on function public.submit_survey_response(
  uuid, uuid, jsonb, boolean, text, text, text, text, text, text, jsonb
) from public, anon, authenticated;
grant execute on function public.submit_survey_response(
  uuid, uuid, jsonb, boolean, text, text, text, text, text, text, jsonb
) to service_role;

revoke execute on function public.survey_tallies(uuid) from public, anon, authenticated;
grant execute on function public.survey_tallies(uuid) to service_role;

comment on table surveys is
  'Server-only survey definitions. RLS enabled with no policies; written by reviewed SQL, read through the service-role key.';
comment on table survey_questions is
  'Server-only survey questions. Keys are stable: answers are stored against them.';
comment on table survey_options is
  'Server-only survey options. Keys are unique per survey so show_if and piped answers can name them.';
comment on table survey_responses is
  'Server-only anonymous survey answers. No names, no IP addresses. Preview answers are flagged and never counted.';
comment on table survey_contacts is
  'Server-only personal data: volunteers who asked to be contacted about a survey. Consent text and time recorded per row.';
